name: Test, Build and push Docker image

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install flake8 pytest
      - name: Analysing the code with Flake8
        run: |
          flake8
      - name: Unit testing with Pytest
        run: |
          pytest
        env:
          FLASK_ENV: testing

  build-and-push:
    needs: test
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3
      - name: Docker Login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: willianpaixao/cl-ea-quandl:latest
          platforms: linux/386,linux/amd64,linux/arm64
