name: Build and push Docker image

on:
  push:
    branches: master

jobs:
  build-and-push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3
      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.0
        with:
          tags: willianpaixao/cl-ea-quandl:latest
          platforms: linux/386,linux/amd64,linux/arm64
          push: true
