name: Test, Build and push Docker image

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install flake8 pytest
      - name: Analysing the code with Flake8
        run: |
          flake8
      - name: Unit testing with Pytest
        run: |
          pytest
        env:
          FLASK_ENV: testing
          QUANDL_API_KEY: ${{ secrets.QUANDL_API_KEY }}

  build-and-push:
    needs: test
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.4
      - name: Docker Login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Gather labels
        id: pre
        run: |
          DOCKER_IMAGE=willianpaixao/cl-ea-quandl
          VERSION=latest
          [[ $GITHUB_REF == refs/tags/* ]] && VERSION=${GITHUB_REF#refs/tags/}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=tags::${DOCKER_IMAGE}:${VERSION}
          echo ::set-output name=version::${VERSION}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.1
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.pre.outputs.tags }}
          platforms: linux/386,linux/amd64,linux/arm64
          build-args: |
            created=${{ steps.pre.outputs.created }}
            revision=${{ github.sha }}
            version=${{ steps.pre.outputs.version }}
          labels: |
            org.opencontainers.image.created=${{ steps.pre.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.pre.outputs.version }}
